name = "echilibru-web"
compatibility_date = "2026-08-14"
compatibility_flags = ["nodejs_compat", "disable_nodejs_process_v2"]

[vars]
NODE_ENV = "production"
SENDER_EMAIL = "onboarding@resend.dev"
RECIPIENT_EMAIL = "alexandru.marius.dragut@gmail.com"
GMAIL_USER="alexandru.marius.dragut@gmail.com"
RESEND_API_KEY

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1